image: continuumio/miniconda3:latest

stages:
  - test
  - build
  - docs
  - deploy
  - release

check:
  stage: test
  before_script:
    - conda create -n esmf -c conda-forge esmpy python=3.12 pip black isort pylint
    - source activate esmf
  script:
    - pip install .
    - black --check --diff --color .
    - isort --check --diff --color .
    - pylint src/finam_regrid
  tags:
    - ufz-intranet

test:
  stage: test
  before_script:
    - conda create -n esmf -c conda-forge esmpy python=3.12 pip
    - source activate esmf
  script:
    - pip install .[test]
    - python -m pytest --cov finam_regrid --cov-report term-missing --cov-report xml:cov.xml -v tests/
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cov.xml
  tags:
    - ufz-intranet

doctest:
  stage: test
  before_script:
    - conda create -n esmf -c conda-forge esmpy python=3.12 pip
    - source activate esmf
  script:
    - pip install --editable .[doc]
    # doctest does not detect tests in code files during the first run.
    # add a dummy build to generate .rst files before the actual tests
    - sphinx-build -b dummy docs/source docs/build
    - sphinx-build -b doctest docs/source docs/build
  tags:
    - ufz-intranet

benchmark:
  stage: test
  before_script:
    - conda create -n esmf -c conda-forge esmpy python=3.12 pip
    - source activate esmf
  script:
    - pip install --editable .[test]
    - python -m pytest -v benchmarks/ --benchmark-histogram bench/bench  --benchmark-sort name
  artifacts:
    paths:
      - bench
  tags:
    - ufz-intranet

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
    GIT_DEPTH: 0  # to have all tags
  script:
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist

documentation:
  stage: docs
  before_script:
    - conda create -n esmf -c conda-forge esmpy python=3.12 pip
    - source activate esmf
  script:
    - pip install --editable .[doc]
    - sphinx-build docs/source docs/build
    - mv docs/build public/
  artifacts:
    paths:
      - public
  tags:
    - ufz-intranet

pages:
  stage: deploy
  script: "true"
  artifacts:
    paths:
      - public
  only:
    - main

pypi_test_release:
  stage: release
  dependencies:
    - build
  script:
    - pip install twine
    - python -m twine upload --skip-existing -r testpypi -u __token__ -p ${TEST_PYPI_TOKEN} dist/*
  artifacts:
    paths:
      - dist
  only:
    - main
    - tags

pypi_release:
  stage: release
  dependencies:
    - build
  script:
    - pip install twine
    - python -m twine upload -u __token__ -p ${PYPI_TOKEN} dist/*
  artifacts:
    paths:
      - dist
  only:
    - tags
